# Generated by Django 3.0.3 on 2020-03-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200227_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='yo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='texts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.yo'),
        ),
    ]
