# Generated by Django 3.0.3 on 2020-03-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200305_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yo',
            old_name='text',
            new_name='texts',
        ),
    ]
