# Generated by Django 3.0.3 on 2020-02-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200219_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subcategory',
        ),
    ]
