# Generated by Django 3.0.3 on 2020-03-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200305_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yo',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='texts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.yo'),
        ),
    ]
