# Generated by Django 3.0.3 on 2020-03-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200305_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yo',
            name='texts',
        ),
        migrations.AddField(
            model_name='yo',
            name='a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='b',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='c',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='d',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='e',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='f',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='g',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='h',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='i',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='j',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='k',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='l',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yo',
            name='m',
            field=models.TextField(blank=True),
        ),
    ]
