# Generated by Django 3.0.3 on 2020-03-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200305_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yo',
            old_name='a',
            new_name='Text',
        ),
    ]
