# Generated by Django 3.0.3 on 2020-02-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_post_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.CharField(choices=[('World', 'World'), ('U.S.', 'U.S.')], default='U.S.', max_length=15),
        ),
    ]
