# Generated by Django 3.0.3 on 2020-03-05 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200305_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='texts',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.yo'),
        ),
    ]
