# Generated by Django 3.0.3 on 2020-02-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_post_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Archeology', 'Archeology'), ('Celebrity News', 'Celebrity News'), ('Conflicts', 'Conflicts'), ('Crime', 'Crime'), ('Disaster', 'Disaster'), ('Education', 'Education'), ('Environment', 'Environment'), ('Immigration', 'Immigration'), ('Music News', 'Music News'), ('Natural Science', 'Natural Science'), ('Religion', 'Religion'), ('Scandals', 'Scandals'), ('Wild Nature', 'Wild Nature'), ('Opinion', 'Opinion')], default='Archeology', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(choices=[('World', 'World'), ('U.S.', 'U.S.'), ('Entertainment', 'Entertainment'), ('Science', 'Science')], default='U.S.', max_length=15),
        ),
    ]
