# Generated by Django 3.0.3 on 2020-03-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200305_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
    ]
