# Generated by Django 3.0.3 on 2020-03-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20200309_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='Text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='b',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='c',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='d',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='e',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='f',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='g',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='h',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='i',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='j',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='k',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='l',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='m',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='yo',
        ),
    ]
