# Generated by Django 3.0.3 on 2020-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20200309_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lastedit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
