# Generated by Django 3.0.3 on 2020-03-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_auto_20200315_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
