# Generated by Django 3.0.3 on 2020-03-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(default='', upload_to='documents/'),
        ),
    ]
