# Generated by Django 3.0.3 on 2020-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_auto_20200315_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
