# Generated by Django 3.0.3 on 2020-03-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_auto_20200320_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p1',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
