# Generated by Django 3.0.3 on 2020-03-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_auto_20200321_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p1',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents/'),
        ),
    ]
