# Generated by Django 3.0.3 on 2020-03-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_auto_20200321_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p1',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
    ]
