# Generated by Django 3.0.3 on 2020-03-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_auto_20200321_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p10',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p11',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p12',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p13',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p2',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p3',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p4',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p5',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p6',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p7',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p8',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='p9',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
    ]
