# Generated by Django 3.0.3 on 2020-03-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_auto_20200321_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
