# Generated by Django 3.0.3 on 2020-03-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_auto_20200323_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.TextField(blank=True),
        ),
    ]
