# Generated by Django 3.0.3 on 2020-03-23 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0057_auto_20200323_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20, null=True)),
                ('Lastname', models.CharField(max_length=20, null=True)),
                ('EmailAddress', models.EmailField(max_length=254, null=True)),
                ('Bio', models.TextField(null=True)),
                ('Username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
