# Generated by Django 3.0.3 on 2020-03-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='EmailAddress',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
