# Generated by Django 3.0.3 on 2020-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Bio',
            field=models.TextField(max_length=102, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
