# Generated by Django 3.0.3 on 2020-03-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_auto_20200326_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Bio',
            field=models.TextField(max_length=95, null=True),
        ),
    ]
