# Generated by Django 2.2.12 on 2020-05-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_trashphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashphoto',
            name='trashphoto',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
