# Generated by Django 2.2.12 on 2020-06-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_auto_20200528_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashphoto',
            name='trashphoto',
            field=models.FileField(default='t', upload_to='documents/'),
        ),
    ]
