# Generated by Django 2.2.12 on 2020-06-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_auto_20200605_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashphoto',
            name='trashphoto',
            field=models.FileField(upload_to='documents/originals/'),
        ),
    ]
