# Generated by Django 2.2.12 on 2020-06-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_auto_20200605_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashphoto',
            name='x1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trashphoto',
            name='x2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trashphoto',
            name='y1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trashphoto',
            name='y2',
            field=models.FloatField(null=True),
        ),
    ]
