# Generated by Django 2.2.12 on 2020-06-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_auto_20200615_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='o3x2',
            new_name='p3x2',
        ),
    ]
