# Generated by Django 2.2.12 on 2020-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0084_auto_20200616_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='x1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='x2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='y1',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='y2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
